-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: schema/abstractSchemaChanges/patch-revsrc-unique-to-pk.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP  INDEX revsrc_rs_unique;
DROP  INDEX revsrc_revid_index;
DROP  INDEX revsrc_timestamp_index;
CREATE TEMPORARY TABLE /*_*/__temp__revsrc AS
SELECT  revsrc_revid,  revsrc_srcworkid,  revsrc_timestamp,  revsrc_user,  revsrc_user_text,  revsrc_comment
FROM  /*_*/revsrc;
DROP  TABLE  /*_*/revsrc;
CREATE TABLE  /*_*/revsrc (    revsrc_revid INTEGER UNSIGNED NOT NULL,    revsrc_srcworkid INTEGER UNSIGNED NOT NULL,    revsrc_timestamp BLOB NOT NULL,    revsrc_user INTEGER UNSIGNED NOT NULL,    revsrc_user_text CLOB NOT NULL,    revsrc_comment CLOB NOT NULL,    PRIMARY KEY(revsrc_revid, revsrc_srcworkid)  );
INSERT INTO  /*_*/revsrc (    revsrc_revid, revsrc_srcworkid, revsrc_timestamp,    revsrc_user, revsrc_user_text, revsrc_comment  )
SELECT  revsrc_revid,  revsrc_srcworkid,  revsrc_timestamp,  revsrc_user,  revsrc_user_text,  revsrc_comment
FROM  /*_*/__temp__revsrc;
DROP  TABLE /*_*/__temp__revsrc;
CREATE INDEX revsrc_revid_index ON  /*_*/revsrc (revsrc_revid);
CREATE INDEX revsrc_timestamp_index ON  /*_*/revsrc (revsrc_timestamp);