-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: schema/abstractSchemaChanges/patch-swsource_links-unique-to-pk.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP  INDEX swsl_work_source_unique;
CREATE TEMPORARY TABLE /*_*/__temp__swsource_links AS
SELECT  swsl_workid,  swsl_sourceid,  swsl_comment
FROM  /*_*/swsource_links;
DROP  TABLE  /*_*/swsource_links;
CREATE TABLE  /*_*/swsource_links (    swsl_workid INTEGER UNSIGNED NOT NULL,    swsl_sourceid INTEGER UNSIGNED NOT NULL,    swsl_comment BLOB DEFAULT '' NOT NULL,    PRIMARY KEY(swsl_workid, swsl_sourceid)  );
INSERT INTO  /*_*/swsource_links (    swsl_workid, swsl_sourceid, swsl_comment  )
SELECT  swsl_workid,  swsl_sourceid,  swsl_comment
FROM  /*_*/__temp__swsource_links;
DROP  TABLE /*_*/__temp__swsource_links;