-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: schema/abstractSchemaChanges/patch-swauthor_links-unique-to-pk.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP  INDEX swal_srcwork_author_unique;
CREATE TEMPORARY TABLE /*_*/__temp__swauthor_links AS
SELECT  swal_srcworkid,  swal_authorid
FROM  /*_*/swauthor_links;
DROP  TABLE  /*_*/swauthor_links;
CREATE TABLE  /*_*/swauthor_links (    swal_srcworkid INTEGER UNSIGNED NOT NULL,    swal_authorid INTEGER UNSIGNED NOT NULL,    PRIMARY KEY(swal_srcworkid, swal_authorid)  );
INSERT INTO  /*_*/swauthor_links (swal_srcworkid, swal_authorid)
SELECT  swal_srcworkid,  swal_authorid
FROM  /*_*/__temp__swauthor_links;
DROP  TABLE /*_*/__temp__swauthor_links;