-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: schema/abstractSchemaChanges/patch-swsource_links-unique-to-pk.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP  INDEX swsl_work_source_unique ON  /*_*/swsource_links;
ALTER TABLE  /*_*/swsource_links
ADD  PRIMARY KEY (swsl_workid, swsl_sourceid);