-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: schema/abstractSchemaChanges/patch-swauthor_links-unique-to-pk.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP  INDEX swal_srcwork_author_unique ON  /*_*/swauthor_links;
ALTER TABLE  /*_*/swauthor_links
ADD  PRIMARY KEY (swal_srcworkid, swal_authorid);