-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: schema/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/swsite (
  sws_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  sws_name VARBINARY(255) NOT NULL,
  sws_short_name VARBINARY(255) NOT NULL,
  sws_site_uri VARBINARY(255) NOT NULL,
  sws_user_uri VARBINARY(255) NOT NULL,
  sws_work_uri VARBINARY(255) NOT NULL,
  UNIQUE INDEX swsite_name (sws_name),
  UNIQUE INDEX swsite_short_name (sws_short_name),
  UNIQUE INDEX swsite_site_uri (sws_site_uri),
  UNIQUE INDEX swsite_user_uri (sws_user_uri),
  UNIQUE INDEX swsite_work_uri (sws_work_uri),
  PRIMARY KEY(sws_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/swauthor (
  swa_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  swa_site INT UNSIGNED NOT NULL,
  swa_user_name VARBINARY(255) DEFAULT NULL,
  swa_real_name VARBINARY(255) DEFAULT NULL,
  swa_uri_part VARBINARY(255) NOT NULL,
  UNIQUE INDEX swauthor_namesite_unique (swa_site, swa_user_name),
  PRIMARY KEY(swa_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/srcwork (
  srcwork_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  srcwork_site INT UNSIGNED NOT NULL,
  srcwork_creator INT UNSIGNED NOT NULL,
  srcwork_date BINARY(14) NOT NULL,
  srcwork_title VARBINARY(255) DEFAULT '' NOT NULL,
  srcwork_uri_part VARBINARY(255) NOT NULL,
  UNIQUE INDEX srcwork_uridate_unique (
    srcwork_site, srcwork_uri_part, srcwork_date
  ),
  PRIMARY KEY(srcwork_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/swauthor_links (
  swal_srcworkid INT UNSIGNED NOT NULL,
  swal_authorid INT UNSIGNED NOT NULL,
  PRIMARY KEY(swal_srcworkid, swal_authorid)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/swsource_links (
  swsl_workid INT UNSIGNED NOT NULL,
  swsl_sourceid INT UNSIGNED NOT NULL,
  swsl_comment VARBINARY(255) DEFAULT '' NOT NULL,
  PRIMARY KEY(swsl_workid, swsl_sourceid)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/revsrc (
  revsrc_revid INT UNSIGNED NOT NULL,
  revsrc_srcworkid INT UNSIGNED NOT NULL,
  revsrc_timestamp BINARY(14) NOT NULL,
  revsrc_user INT UNSIGNED NOT NULL,
  revsrc_user_text TEXT NOT NULL,
  revsrc_comment TEXT NOT NULL,
  UNIQUE INDEX revsrc_rs_unique (revsrc_revid, revsrc_srcworkid),
  INDEX revsrc_revid_index (revsrc_revid),
  INDEX revsrc_timestamp_index (revsrc_timestamp)
) /*$wgDBTableOptions*/;
