-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/CreditsSource/schema/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/swsite (
  sws_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  sws_name VARBINARY(255) NOT NULL,
  sws_short_name VARBINARY(255) NOT NULL,
  sws_site_uri VARBINARY(255) NOT NULL,
  sws_user_uri VARBINARY(255) NOT NULL,
  sws_work_uri VARBINARY(255) NOT NULL,
  UNIQUE INDEX swsite_name (sws_name),
  UNIQUE INDEX swsite_short_name (sws_short_name),
  UNIQUE INDEX swsite_site_uri (sws_site_uri),
  UNIQUE INDEX swsite_user_uri (sws_user_uri),
  UNIQUE INDEX swsite_work_uri (sws_work_uri),
  PRIMARY KEY(sws_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/srcwork (
  srcwork_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  srcwork_site INT UNSIGNED NOT NULL,
  srcwork_creator INT UNSIGNED NOT NULL,
  srcwork_date BINARY(14) NOT NULL,
  srcwork_title VARBINARY(255) DEFAULT '' NOT NULL,
  srcwork_uri_part VARBINARY(255) NOT NULL,
  UNIQUE INDEX srcwork_uridate_unique (
    srcwork_site, srcwork_uri_part, srcwork_date
  ),
  PRIMARY KEY(srcwork_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/revsrc (
  revsrc_revid INT UNSIGNED NOT NULL,
  revsrc_srcworkid INT UNSIGNED NOT NULL,
  revsrc_timestamp BINARY(14) NOT NULL,
  revsrc_user INT UNSIGNED NOT NULL,
  revsrc_user_text TEXT NOT NULL,
  revsrc_comment TEXT NOT NULL,
  INDEX revsrc_revid_index (revsrc_revid),
  INDEX revsrc_timestamp_index (revsrc_timestamp),
  PRIMARY KEY(revsrc_revid, revsrc_srcworkid)
) /*$wgDBTableOptions*/;
