-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/CreditsSource/schema/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE swsite (
  sws_id SERIAL NOT NULL,
  sws_name TEXT NOT NULL,
  sws_short_name TEXT NOT NULL,
  sws_site_uri TEXT NOT NULL,
  sws_user_uri TEXT NOT NULL,
  sws_work_uri TEXT NOT NULL,
  PRIMARY KEY(sws_id)
);

CREATE UNIQUE INDEX swsite_name ON swsite (sws_name);

CREATE UNIQUE INDEX swsite_short_name ON swsite (sws_short_name);

CREATE UNIQUE INDEX swsite_site_uri ON swsite (sws_site_uri);

CREATE UNIQUE INDEX swsite_user_uri ON swsite (sws_user_uri);

CREATE UNIQUE INDEX swsite_work_uri ON swsite (sws_work_uri);


CREATE TABLE srcwork (
  srcwork_id SERIAL NOT NULL,
  srcwork_site INT NOT NULL,
  srcwork_creator INT NOT NULL,
  srcwork_date TIMESTAMPTZ NOT NULL,
  srcwork_title TEXT DEFAULT '' NOT NULL,
  srcwork_uri_part TEXT NOT NULL,
  PRIMARY KEY(srcwork_id)
);

CREATE UNIQUE INDEX srcwork_uridate_unique ON srcwork (
  srcwork_site, srcwork_uri_part, srcwork_date
);


CREATE TABLE revsrc (
  revsrc_revid INT NOT NULL,
  revsrc_srcworkid INT NOT NULL,
  revsrc_timestamp TIMESTAMPTZ NOT NULL,
  revsrc_user INT NOT NULL,
  revsrc_user_text TEXT NOT NULL,
  revsrc_comment TEXT NOT NULL,
  PRIMARY KEY(revsrc_revid, revsrc_srcworkid)
);

CREATE INDEX revsrc_revid_index ON revsrc (revsrc_revid);

CREATE INDEX revsrc_timestamp_index ON revsrc (revsrc_timestamp);
